name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', whichever is your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # So we do not accidentally commit using the GITHUB_TOKEN

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}